### ISSUE TITLE
needs LICENSE

### ISSUE THREAD

**Issue by broady** [kris-nova/lolgopher#13]
🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 

also, CrowdSurge/banner doesn't have a LICENSE

🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈 🌈 🏳️‍🌈

**Comment by broady** [comment]
🦄

**Comment by robjloranger** [comment]
What license @kris-nova? Apache?

**Comment by kris-nova** [comment]
yeah apache works!
